---
resources:
- name: project-git
  type: git
  source:
    uri: git@github.com:bbmoz/ci-docker.git
    branch: master

- name: npm-cache
  type: s3
  source:
    endpoint: minio-storage:9000
    bucket: npm
    regex: npm-(.*).zip
    disable_ssl: true
    access_key_id: ${MINIO_ACCESS_KEY_ID}
    secret_access_key: ${MINIO_SECRET_ACCESS_KEY}

jobs:
- name: build
  plan:
  - aggregate:
    - get: project-git
      trigger: true
    - get: npm-cache
  - task: build
    file: ci-docker/example/tasks/build/task.yml
  - put: npm-cache
    params:
      file: new-npm-cache/npm-*.zip

- name: unit-test
  plan:
  - aggregate:
    - get: project-git
      passed:
      - build
    - get: npm-cache
      passed:
      - build
  - task: unit-test
    file: ci-docker/example/tasks/unit-test/unit-test.yml

# etc
