version: "3"

services:
    concourse-db:
        image: postgres:9.5
        environment:
            POSTGRES_DB: concourse
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            PGDATA: /database

    concourse-web:
        image: concourse/concourse
        command: web
        depends_on: [concourse-db]
        ports: ["8080:8080"]
        volumes: ["./keys/web:/concourse-keys"]
        restart: unless-stopped
        environment:
            CONCOURSE_BASIC_AUTH_USERNAME: ${WEB_USER}
            CONCOURSE_BASIC_AUTH_PASSWORD: ${WEB_PASS}
            CONCOURSE_EXTERNAL_URL: "${WEB_EXTERNAL_URL}"
            CONCOURSE_POSTGRES_HOST: concourse-db
            CONCOURSE_POSTGRES_USER: ${DB_USER}
            CONCOURSE_POSTGRES_PASSWORD: ${DB_PASS}
            CONCOURSE_POSTGRES_DATABASE: concourse

    concourse-worker:
        image: concourse/concourse
        command: worker
        depends_on: [concourse-web]
        volumes: ["./keys/worker:/concourse-keys"]
        privileged: true
        environment:
            CONCOURSE_TSA_HOST: concourse-web

    docker-registry:
        image: registry:2
        ports: ["5000:5000"]
        restart: always

    minio-storage:
        image: minio/minio
        command: server /export
        ports: ["9000:9000"]
