---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 127.0.0.1:5000/ci
    insecure_registries:
    - "127.0.0.1:5000"

inputs:
- name: git
- name: npm-cache

run:
  path: example/tasks/unit-test/run.sh
  dir: git
